### ISSUE TITLE
Does this supports opencv?

### ISSUE THREAD

**Issue by twmht** [komrad36/CUDAFLERP#2]
Hi,

I would like to use opencv input format.

for example,

```
Mat im = cv::imread('test.jpg');
float *im_data = im.data;
// copy host data to device
// resize im_data
```

the format of opencv is RGB,RGB,RGB...

Each channel is 8 bit.

Does your provided kernel function support this format?

**Comment by komrad36** [comment]
Please read the README before opening an issue for an easily answerable question.

"The file CUDAFLERP.h exposes two extremely high performance GPU resize operations, CUDAFLERP (bilinear interpolation), and CUDAFNERP (nearest neighbor interpolation), for **32-bit float grayscale data**.

For **8-bit unsigned integer data, see the CUDALERP project instead**.."

And from CUDALERP's README:

"The file CUDALERP.h exposes two extremely high performance GPU resize operations, CUDALERP (bilinear interpolation), and CUDANERP (nearest neighbor interpolation), for 8-bit unsigned integer (i.e. grayscale) data."

This makes it very clear that these projects support 32-bit float or 8-bit unsigned grayscale, not RGB, data.

(They're intended for computer vision, where grayscale is usually wise. It would not be difficult to modify these projects for RGB data if that's what you need.)
